version: '3.7'
services:
  mailserver:
    image: 'namshi/smtp'
    ports:
      - '25:25'
  mariadb:
    image: 'mariadb:latest'
    healthcheck:
       test: ["CMD", "mysqladmin", "-p${DB_ROOT_PWD}", "ping", "-h", "127.0.0.1"] 
       interval: 10s
       timeout: 8s
       retries: 10
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql/
  phabricator:
    build: ./phabricator
    command: bash -c "./phabricator/bin/storage upgrade && ./phabricator/bin/phd start && apachectl -D FOREGROUND"
    command: bash -c "apachectl -D FOREGROUND"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: volume
        source: phabricator_data
        target: /data
    depends_on:
      - mariadb
volumes:
  mariadb_data:
  phabricator_data:
